### PR TITLE
catch acceptable and user statuses

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by abelsiqueira** [comment]
Needs https://github.com/JuliaRegistries/General/pull/2767

**Comment by abelsiqueira** [comment]
Needs to add a limit to SolverTools.jl for >= 0.1.4

**Comment by dpo** [comment]
Thanks. Done.

**Comment by abelsiqueira** [comment]
The documentation failure does not seem to be related, so I'll merge and open an issue

**Comment by abelsiqueira** [comment]
Thanks

**Pull request merged**
