### PR TITLE
option: pass initial multipliers to IPOPT

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
@PEPERSO I haven't yet tested this but it could be useful for NCL.

**Comment by abelsiqueira** [comment]
It looks like the solver also needs the option `warm_start_init_point = "yes"`.
I tested using the solution and multipliers of a problem as the starting point for the same, and it also needs `warm_start_bound_push=1e-8` and `warm_start_mult_bound_push=1e-8` to not move the initial point too much. It still made 2 iterations.

**Comment by dpo** [comment]
I'm only getting back to this. I now set `warm_start_init_point = "yes"` when the user specifies x0, y0, zL and zU. I'm not setting the other options because in general, we can't expect a solve in zero iterations. If the initial guess is on the boundary, IPOPT will normally want to move it. The warm start option is for good (interior) initial guesses, not for points on the boundary. Still, the user could set those options themselves.

**Comment by abelsiqueira** [comment]
Thank you.

**Pull request merged**
