### PR TITLE
Use a fixed name for IPOPT log file

### PR DESCRIPTION
**Pull request by abelsiqueira**

### CODE REVIEW

**Comment by dpo** [comment]
Why?

**Comment by abelsiqueira** [comment]
While working on JSOFilter I used `ipopt` every iteration and after running on a few problems if filled my `/tmp` folder with temporary files. A tried removing them in #28, but Windows doesn't like that.

**Comment by dpo** [comment]
#28 seems like the right approach though. Do you think it could be a bug in IPOPT on Windows, that it doesn't close the log file?

**Comment by abelsiqueira** [comment]
No, it doesn't close on Linux either. Or maybe it's the Julia call that doesn't close it. Either way, the file remains open for a while. On Linux I can just delete it, but Windows doesn't let me.

**Comment by dpo** [comment]
How about we pass it in as an argument with default value `tempname()`?

**Comment by abelsiqueira** [comment]
Makes sense. Technically it already handles that. I can pass `output_file=...` and it would parse on line 104. So I guess we can close this

**Comment by dpo** [comment]
Right. Even better. The solution is already implemented!

**Pull request closed without merging**
